# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TechVibeSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.9'

  # Pods for TechVibeSwift

  target 'TechVibeSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TechVibeSwiftUITests' do
    # Pods for testing
  end

end
